{% set version = "4.4.4" %}

package:
  name: qtconsole
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/q/qtconsole/qtconsole-{{ version }}.tar.gz
  sha256: a667558c7b1e1442a2e5bcef1686c55e096efd0b58d8b2a0a8415f4579991ee3

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - jupyter-qtconsole = qtconsole.qtconsoleapp:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ipykernel >=4.1
    - jupyter_client >=4.1
    - jupyter_core
    - pygments
    - pyqt
    - traitlets

test:
  commands:
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'jupyter qtconsole --help'

  imports:
    - qtconsole
    - qtconsole.tests

about:
  home: http://jupyter.org
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Jupyter Qt console
  description: |
    A rich Qt-based console for working with Jupyter kernels, supporting rich
    media output, session export, and more. The Qt console is a very
    lightweight application that largely feels like a terminal, but provides
    a number of enhancements only possible in a GUI, such as inline figures,
    proper multiline editing with syntax highlighting, graphical calltips, and
    more.
  doc_url: https://qtconsole.readthedocs.org/en/stable/
  dev_url: https://github.com/jupyter/qtconsole
  doc_source_url: https://github.com/jupyter/qtconsole/tree/master/docs

extra:
  recipe-maintainers:
    - Carreau
    - ccordoba12
    - jakirkham
    - minrk
    - takluyver
    - ocefpaf
