{% set version = "5.1.1" %}

package:
  name: qtconsole
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/q/qtconsole/qtconsole-{{ version }}.tar.gz
  sha256: bbc34bca14f65535afcb401bc74b752bac955e5313001ba640383f7e5857dc49

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-qtconsole = qtconsole.qtconsoleapp:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyqt
    - traitlets
    - ipython_genutils
    - jupyter_core
    - jupyter_client >=4.1
    - pygments
    - ipykernel >=4.1  # not a real dependency, but require the reference kernel
    - qtpy

test:
  commands:
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'jupyter qtconsole --help'

  imports:
    - qtconsole
    - qtconsole.tests

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Jupyter Qt console
  description: |
    A rich Qt-based console for working with Jupyter kernels, supporting rich
    media output, session export, and more. The Qt console is a very
    lightweight application that largely feels like a terminal, but provides
    a number of enhancements only possible in a GUI, such as inline figures,
    proper multiline editing with syntax highlighting, graphical calltips, and
    more.
  doc_url: https://qtconsole.readthedocs.org/en/stable/
  dev_url: https://github.com/jupyter/qtconsole
  doc_source_url: https://github.com/jupyter/qtconsole/tree/master/docs

extra:
  recipe-maintainers:
    - Carreau
    - ccordoba12
    - jakirkham
    - minrk
    - takluyver
    - ocefpaf
