{% set version = "5.6.0" %}

package:
  name: qtconsole-base
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/q/qtconsole/qtconsole-{{ version }}.tar.gz
  sha256: 4c82120a3b53a3d36e3f76e6a1a26ffddf4e1ce2359d56a19889c55e1d73a436

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-qtconsole = qtconsole.qtconsoleapp:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - traitlets
    - jupyter_core
    - jupyter_client >=4.1
    - pygments
    - ipykernel >=4.1  # not a real dependency, but require the reference kernel
    - qtpy >=2.4.0
    - packaging

test:
  imports:
    - qtconsole
    - qtconsole.tests

outputs:
  - name: qtconsole-base
  - name: qtconsole
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
        - {{ pin_subpackage('qtconsole-base', max_pin='x.x.x') }}
      run:
        - python >=3.8
        - {{ pin_subpackage('qtconsole-base', max_pin='x.x.x') }}
        - pyqt
    test:
      commands:
        - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'jupyter qtconsole --help'

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Jupyter Qt console
  description: |
    A rich Qt-based console for working with Jupyter kernels, supporting rich
    media output, session export, and more. The Qt console is a very
    lightweight application that largely feels like a terminal, but provides
    a number of enhancements only possible in a GUI, such as inline figures,
    proper multiline editing with syntax highlighting, graphical calltips, and
    more.
  doc_url: https://qtconsole.readthedocs.org/en/stable/
  dev_url: https://github.com/jupyter/qtconsole
  doc_source_url: https://github.com/jupyter/qtconsole/tree/master/docs

extra:
  recipe-maintainers:
    - Carreau
    - ccordoba12
    - jakirkham
    - minrk
    - takluyver
    - ocefpaf
  feedstock-name: qtconsole
